# Generated by Django 4.2.13 on 2024-05-14 15:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Grupa cenowa"
                    ),
                ),
                (
                    "discount_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Przyznany rabat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupa cenowa",
                "verbose_name_plural": "Grupy cenowe",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nazwa"),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=255, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Opis"
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={
                "ordering": ["-user__pk"],
                "verbose_name": "Profil użytkownika",
                "verbose_name_plural": "Profile użytkowników",
            },
        ),
        migrations.CreateModel(
            name="ProductPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Cena"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data utworzenia ceny",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.product",
                        verbose_name="Produkt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cena produktu",
                "verbose_name_plural": "Ceny produktów",
                "ordering": ["-product__name", "-created_date"],
            },
        ),
        migrations.CreateModel(
            name="CustomerPriceGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Klient",
                    ),
                ),
                (
                    "price_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.pricegroup",
                        verbose_name="Grupa cenowa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupa cenowa klienta",
                "verbose_name_plural": "Grupy cenowe klientów",
                "ordering": ["customer__username"],
                "unique_together": {("customer", "price_group")},
            },
        ),
    ]
