# Generated by Django 4.2.13 on 2024-05-15 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_alter_product_description_alter_product_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="is_menu",
            new_name="is_main",
        ),
    ]
