# Generated by Django 4.2.13 on 2024-05-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_rename_is_menu_category_is_main"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricegroup",
            name="discount_rate",
            field=models.IntegerField(
                default=0, verbose_name="Przyznany rabat"
            ),
        ),
    ]
