# Generated by Django 4.2.13 on 2024-05-15 10:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("web", "0007_alter_pricegroup_discount_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        db_index=True,
                        default=datetime.datetime(
                            2024, 5, 15, 10, 34, 1, 341821
                        ),
                        verbose_name="Data utworzenia koszyka",
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data aktualizacji"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Cena"
                    ),
                ),
                (
                    "amount_with_discount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Cena z rabatem",
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Rabat"
                    ),
                ),
                (
                    "info",
                    models.TextField(
                        blank=True, null=True, verbose_name="Komentarz"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Klient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zapisany koszyk",
                "verbose_name_plural": "Zapisane koszyki",
                "ordering": ["-created_date"],
            },
        ),
        migrations.AlterField(
            model_name="pricegroup",
            name="discount_rate",
            field=models.IntegerField(
                default=0, verbose_name="Przyznany rabat w %"
            ),
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Nazwa"
                    ),
                ),
                ("qty", models.IntegerField(default=1, verbose_name="Ilość")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Cena"
                    ),
                ),
                (
                    "discount",
                    models.IntegerField(default=0, verbose_name="Rabat"),
                ),
                (
                    "info",
                    models.TextField(
                        blank=True, null=True, verbose_name="Komentarz"
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="web.cart",
                        verbose_name="Koszyk",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produkt w koszyku",
                "verbose_name_plural": "Produkty w koszyku",
                "ordering": ["name"],
            },
        ),
    ]
