# Generated by Django 4.2.13 on 2024-05-15 10:35

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0008_cart_alter_pricegroup_discount_rate_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="created_date",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(2024, 5, 15, 10, 35, 1, 579873),
                verbose_name="Data utworzenia koszyka",
            ),
        ),
    ]
