# Generated by Django 4.2.13 on 2024-05-15 10:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0009_alter_cart_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="created_date",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Data utworzenia koszyka",
            ),
        ),
    ]
