# Generated by Django 4.2.13 on 2024-05-15 10:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("web", "0011_shipment"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Nazwa"
                    ),
                ),
                ("qty", models.IntegerField(default=1, verbose_name="Ilość")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Cena"
                    ),
                ),
                (
                    "discount",
                    models.IntegerField(default=0, verbose_name="Rabat"),
                ),
                (
                    "info",
                    models.TextField(
                        blank=True, null=True, verbose_name="Komentarz"
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="web.cart",
                        verbose_name="Koszyk",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="web.product",
                        verbose_name="Produkt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produkt w koszyku",
                "verbose_name_plural": "Produkty w koszyku",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        db_index=True,
                        default=datetime.datetime(
                            2024, 5, 15, 10, 53, 28, 31768
                        ),
                        verbose_name="Data utworzenia zamówienia",
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data aktualizacji"
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        max_length=255, verbose_name="Numer zamówienia"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Nowe"),
                            (1, "W trakcie płatności"),
                            (2, "Opłacone"),
                            (3, "Do zapłaty"),
                            (4, "Płatność nieudana"),
                            (5, "W trakcie realizacji"),
                            (6, "W dostawie"),
                            (7, "Dostarczone"),
                            (8, "Zwrócone"),
                            (9, "Gotowe do odbioru"),
                            (10, "Zrealizowane"),
                            (11, "Anulowane"),
                        ],
                        default=0,
                        verbose_name="Status",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(
                        max_length=255, verbose_name="Imię i nazwisko klienta"
                    ),
                ),
                (
                    "client_email",
                    models.EmailField(
                        max_length=255, verbose_name="Email klienta"
                    ),
                ),
                (
                    "client_phone",
                    models.CharField(
                        max_length=15, verbose_name="Telefon klienta"
                    ),
                ),
                (
                    "client_address",
                    models.CharField(
                        max_length=255, verbose_name="Adres klienta"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Cena"
                    ),
                ),
                (
                    "amount_with_discount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Cena z rabatem",
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Rabat"
                    ),
                ),
                (
                    "info",
                    models.TextField(
                        blank=True, null=True, verbose_name="Komentarz"
                    ),
                ),
                (
                    "payment_method",
                    models.IntegerField(
                        choices=[
                            (0, "Przelew tradycyjny"),
                            (1, "Przelew online"),
                            (2, "Karta kredytowa"),
                            (3, "Gotówka"),
                        ],
                        default=0,
                        verbose_name="Status",
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data płatności"
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Identyfikator płatności",
                    ),
                ),
                (
                    "order_code",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Kod płatności",
                    ),
                ),
                (
                    "invoice",
                    models.BooleanField(default=False, verbose_name="Faktura"),
                ),
                (
                    "email_notification",
                    models.BooleanField(
                        default=True, verbose_name="Czy wysyłac email"
                    ),
                ),
                (
                    "overriden_invoice_number",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nadpisz numer faktury",
                    ),
                ),
                (
                    "overriden_invoice_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Nadpisz datę faktury",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Klient",
                    ),
                ),
                (
                    "delivery_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.shipment",
                        verbose_name="Sposób dostawy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zamówienie",
                "verbose_name_plural": "Zamówienia",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Nazwa"
                    ),
                ),
                ("qty", models.IntegerField(default=1, verbose_name="Ilość")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Cena"
                    ),
                ),
                (
                    "discount",
                    models.IntegerField(default=0, verbose_name="Rabat"),
                ),
                (
                    "info",
                    models.TextField(
                        blank=True, null=True, verbose_name="Komentarz"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="web.order",
                        verbose_name="Koszyk",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="web.product",
                        verbose_name="Produkt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produkt w zamówieniu",
                "verbose_name_plural": "Produkty w zamówieniu",
                "ordering": ["name"],
            },
        ),
        migrations.DeleteModel(
            name="Item",
        ),
    ]
