# Generated by Django 4.2.13 on 2024-05-15 10:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0012_cartitem_order_orderitem_delete_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_date",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Data utworzenia zamówienia",
            ),
        ),
    ]
