# Generated by Django 5.0.6 on 2024-06-28 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0017_category_main"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="prev_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prev_products",
                to="web.category",
                verbose_name="Poprzednia kategoria",
            ),
        ),
    ]
